// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using chiasma_ef_core.Data;

namespace chiasma_ef_core.Data.Migrations
{
    [DbContext(typeof(gtdb2_devel_eeContext))]
    [Migration("20180614054539_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("chiasma_ef_core.Data.Plate", b =>
                {
                    b.Property<int>("PlateId")
                        .HasColumnName("plate_id");

                    b.Property<int?>("BeadChipInfoId")
                        .HasColumnName("bead_chip_info_id");

                    b.Property<string>("Comment")
                        .HasColumnName("comment")
                        .HasMaxLength(1024)
                        .IsUnicode(false);

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnName("identifier")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnName("method")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<int?>("PlateNumber")
                        .HasColumnName("plate_number");

                    b.Property<int>("PlateTypeId")
                        .HasColumnName("plate_type_id");

                    b.Property<string>("PlateUsage")
                        .IsRequired()
                        .HasColumnName("plate_usage")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<int?>("SampleSeriesId")
                        .HasColumnName("sample_series_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("status")
                        .HasDefaultValueSql("('Active')")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.HasKey("PlateId");

                    b.HasIndex("Identifier")
                        .IsUnique()
                        .HasName("plate_UQ");

                    b.ToTable("plate");
                });
#pragma warning restore 612, 618
        }
    }
}
